spring:
  jackson:
    default-property-inclusion: non_null
  http:
    converters:
      preferred-json-mapper: jackson

feign:
  client:
    default-to-properties: true
    default-config: default
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        decode404: false
      #        errorDecoder: feign.codec.ErrorDecoder.Default
      Provider2External:
        connectTimeout: 30000
        readTimeout: 70000
        loggerLevel: FULL

Provider2External:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: ${provider2.external.host:https://localhost:8016}
    ConnectTimeout: 60000
    ReadTimeout: 30000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3