logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    initialize: false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:~/${h2dbname:dg-h2-db};AUTO_SERVER=true;AUTO_SERVER_PORT=${h2dbport:7999};DB_CLOSE_ON_EXIT=FALSE;MODE=ORACLE
      username: sa
      password:
    continue-on-error: true
    platform: h2
    data: data
    schema: schema



